In [12]:
import pandas as pd
import numpy as np

In [122]:
data=pd.read_csv('spam.csv')

In [123]:
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [124]:
data.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [125]:
#def get_spam_number(x):
    #if x=='spam':
        #return 1
    #return 0             

    ### both code are same  one is lambda function other def 

In [126]:
data['spam']=data.Category.apply(lambda x:1 if x=='spam' else 0)

In [127]:
data.shape

(5572, 3)

In [128]:
data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(data.Message,data.spam,test_size=0.2)

NameError: name 'data' is not defined

In [6]:
x_train.shape

NameError: name 'x_train' is not defined

In [7]:
x_test.shape

NameError: name 'x_test' is not defined

In [8]:
type(x_train)

NameError: name 'x_train' is not defined

In [9]:
x_train[:5]

NameError: name 'x_train' is not defined

In [10]:
x_train[:5][969]

NameError: name 'x_train' is not defined

In [11]:
type(x_test)

NameError: name 'x_test' is not defined

In [136]:
y_train[:5]

4191    0
697     0
969     0
3860    1
1401    0
Name: spam, dtype: int64

In [137]:
type(x_train.values)

numpy.ndarray

In [ ]:
#Create bag of words representation using CountVectorizer

In [138]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
x_train_CV=v.fit_transform(x_train.values)
x_train_CV

<4457x7762 sparse matrix of type '<class 'numpy.int64'>'
	with 59089 stored elements in Compressed Sparse Row format>

In [139]:
x_train_CV.toarray()     #### sparse matrix of type   in this vector  more ZEROS  and less numbers  this called sparse matrix 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [140]:
x_train_CV.toarray()[:3][1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [141]:
x_train_CV.shape         #### 7763 unique words  and 4457 email     

(4457, 7762)

In [142]:
v.get_feature_names_out().shape

(7762,)

In [158]:
v.get_feature_names_out()[6331]

'sorry'

In [ ]:
dir(v)

In [ ]:
v.vocabulary_

In [150]:
x_train_np=x_train_CV.toarray()
x_train_np[:4][1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [151]:
np.where(x_train_np[0]!=0)

(array([1637, 4051, 4182, 6331], dtype=int64),)

In [160]:
x_train[:4][4191]

"Sorry, I'll call later"

In [162]:
x_train_np[0][6331]                            ### THIS VECTOR

1

In [ ]:
##Train the naive bayes model

In [164]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()
model.fit(x_train_CV,y_train)

MultinomialNB()

In [165]:
x_test_CV=v.transform(x_test)

In [167]:
from sklearn.metrics import classification_report

y_pred=model.predict(x_test_CV)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       972
           1       0.98      0.94      0.96       143

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [171]:
emails=["Nah I don't think he goes to usf, he lives around here though","Even my brother is not like to speak with me. They treat me like aids patent"]

emails_count=v.transform(emails)
model.predict(emails_count)

array([0, 0], dtype=int64)

In [ ]:
#####Train the model using sklearn pipeline and reduce number of lines of code

In [3]:
from sklearn.pipeline import Pipeline 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [4]:
from sklearn.pipeline import Pipeline 
clf=Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB())
             ])
clf.fit(x_train,y_train)
y_pred=clf.predict(x_test)
print(classification_report(y_test,y_pred))

NameError: name 'x_train' is not defined